import 'dart:async';
import 'dart:ffi';
import 'package:flutter/services.dart';

enum ZIMErrorCode {
  success,
  failed,

  commonModuleParamsInvalid,
  commonModuleEngineNotInit,
  commonModuleInvalidAppID,
  commonModuleTriggerSDKFrequencyLimit,
  commonModuleTriggerServerFrequencyLimit,
  commonModuleSwitchServerError,
  commonModuleIMServerError,
  commonModuleIMDataBaseError,
  commonModuleUploadLogError,

  networkModuleCommonError,
  networkModuleServerError,
  networkModuleTokenInvalid,
  networkModuleNetworkError,
  networkModuleTokenExpired,
  networkModuleTokenVersionError,
  networkModuleUserHasAlreadyLogged,
  networkModuleUserIsNotLogged,

  messageModuleCommonError,
  messageModuleServerError,
  messageModuleSendMessageFailed,
  messageModuleTargetDoseNotExist,
  messageModuleCallError,
  messageModuleCancelCallError,
  messageModuleCallServerError,
  messageModuleIsNotInvitor,
  messageModuleIsNotInvitee,
  messageModuleCallAlreadyExists,
  messageModuleCallDoseNotExist,

  roomModuleCommonError,
  roomModuleServerError,
  roomModuleCreateRoomError,
  roomModuleJoinRoomError,
  roomModuleLeaveRoomError,
  roomModuleUserIsNotInTheRoom,
  roomModuleTheRoomDoseNotExist,
  roomModuleTheRoomAlreadyExists,
  roomModuleTheNumberOfExistingRoomsHasReachedLimit,
  roomModuleTheNumberOfJoinedRoomsHasReachedLimit,
  roomModuleRoomAttributesCommonError,
  roomModuleRoomAttributesOperationFailedCompletely,
  roomModuleRoomAttributesOperationFailedPartly,
  roomModuleRoomAttributesQueryFailed,
  roomModuleTheNumberOfRoomAttributesExceedsLimit,
  roomModuleTheLengthOfRoomAttributeKeyExceedsLimit,
  roomModuleTheLengthOfRoomAttributeValueExceedsLimit,
  roomModuleTheTotalLengthOfRoomAttributesValueExceedsLimit,

  zpnsModulePushIDInvalid,

  groupModuleCommonError,
  groupModuleServerError,
  groupModuleCreateGroupError,
  groupModuleDismissGroupError,
  groupModuleJoinGroupError,
  groupModuleLeaveGroupError,
  groupModuleKickoutGroupMemberError,
  groupModuleInviteUserIntoGroupError,
  groupModuleTransferOwnerError,
  groupModuleUpdateGroupInfoError,
  groupModuleQueryGroupInfoError,
  groupModuleGroupAttributesOperationFailed,
  groupModuleGroupAttributesQueryFailed,
  groupModuleUpdateGroupMemberInfoError,
  groupModuleQueryGroupMemberInfoError,
  groupModuleQueryGroupListError,
  groupModuleQueryGroupMemberListError,
  groupModuleUserIsNotInTheGroup,
  groupModuleMemberIsAlreadyInTheGroup,
  groupModuleGroupDoseNotExist,
  groupModuleGroupAlreadyExists,
  groupModuleGroupMemberHasReachedLimit,
  groupModuleGroupAttributeDoseNotExist,
  groupModuleTheNumberOfGroupAttributesExceedsLimit,
  groupModuleTheLengthOfGroupAttributeKeyExceedsLimit,
  groupModuleTheLengthOfGroupAttributeValueExceedsLimit,
  groupModuleTheTotalLengthOfGroupAttributeValueExceedsLimit,
  groupModuleNoCorrespondingOperationAuthority,
  groupModuleGroupDataBaseError,

  conversationModuleCommonError,
  conversationModuleServerError,
  conversationModuleConversationDoseNotExist,

  dataBaseModuleOpenDataBaseError,
  dataBaseModuleModifyDataBaseError,
  dataBaseModuleDeleteDataBaseError,
  dataBaseModuleSeleteDataBaseError
}
